/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface InfoComponent {
    }
    interface SliderComponent {
        "currentChoice": number;
    }
    interface SwiperComponent {
    }
}
export interface InfoComponentCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLInfoComponentElement;
}
export interface SliderComponentCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSliderComponentElement;
}
declare global {
    interface HTMLInfoComponentElement extends Components.InfoComponent, HTMLStencilElement {
    }
    var HTMLInfoComponentElement: {
        prototype: HTMLInfoComponentElement;
        new (): HTMLInfoComponentElement;
    };
    interface HTMLSliderComponentElement extends Components.SliderComponent, HTMLStencilElement {
    }
    var HTMLSliderComponentElement: {
        prototype: HTMLSliderComponentElement;
        new (): HTMLSliderComponentElement;
    };
    interface HTMLSwiperComponentElement extends Components.SwiperComponent, HTMLStencilElement {
    }
    var HTMLSwiperComponentElement: {
        prototype: HTMLSwiperComponentElement;
        new (): HTMLSwiperComponentElement;
    };
    interface HTMLElementTagNameMap {
        "info-component": HTMLInfoComponentElement;
        "slider-component": HTMLSliderComponentElement;
        "swiper-component": HTMLSwiperComponentElement;
    }
}
declare namespace LocalJSX {
    interface InfoComponent {
        "onEditTrigger"?: (event: InfoComponentCustomEvent<any>) => void;
    }
    interface SliderComponent {
        "currentChoice"?: number;
        "onKeyDownEvent"?: (event: SliderComponentCustomEvent<any>) => void;
    }
    interface SwiperComponent {
    }
    interface IntrinsicElements {
        "info-component": InfoComponent;
        "slider-component": SliderComponent;
        "swiper-component": SwiperComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "info-component": LocalJSX.InfoComponent & JSXBase.HTMLAttributes<HTMLInfoComponentElement>;
            "slider-component": LocalJSX.SliderComponent & JSXBase.HTMLAttributes<HTMLSliderComponentElement>;
            "swiper-component": LocalJSX.SwiperComponent & JSXBase.HTMLAttributes<HTMLSwiperComponentElement>;
        }
    }
}
